<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.section", 
	"catalog_block", 
	array(
		"IBLOCK_TYPE" => "aspro_mshop_catalog",
		"IBLOCK_ID" => \Bitrix\Main\Config\Option::get("aspro.mshop", "CATALOG_IBLOCK_ID", 14),
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_COUNT" => ($arParams["LINKED_ELEMENST_PAGE_COUNT"] ? $arParams["LINKED_ELEMENST_PAGE_COUNT"] : 20),
		"LINE_ELEMENT_COUNT" => "",
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"OFFERS_LIMIT" => "10",
		"SECTION_URL" => "",
		"DETAIL_URL" => "",
		"BASKET_URL" => SITE_DIR."basket/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
	"SALE_STIKER" => ($arParams["SALE_STIKER"] ? $arParams["SALE_STIKER"] : "SALE_TEXT"),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "100000",
		"CACHE_GROUPS" => "Y",
		"DISPLAY_COMPARE" => "Y",
		"PRICE_CODE" => array(
			0 => "Розница ООО Благопар",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_PROPERTIES" => array(
		),
		"CONVERT_CURRENCY" => "N",
		"FILTER_NAME" => $arParams["CATALOG_FILTER_NAME"],
		"SHOW_BUY_BUTTONS" => $arParams["SHOW_BUY_BUTTONS"],
		"USE_PRODUCT_QUANTITY" => "Y",
		"INIT_SLIDER" => "Y",
		"COMPONENT_TEMPLATE" => "products_slider",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"HIDE_NOT_AVAILABLE" => "Y",
		'HIDE_NOT_AVAILABLE_OFFERS' => "Y",
		"OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "NAME",
			2 => "",
		),
		"OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"INCLUDE_SUBSECTIONS" => "Y",
		"SHOW_ALL_WO_SECTION" => "Y",
		"DISPLAY_TYPE" => "block",
		"TYPE_SKU" => "TYPE_1",
		"LINKED_ITEMS" => false,  // отвечает за вывод товаров как "привязанных" к элементу другого инфоблока (без цены, кол-ва и кнопки "в корзину")
		"PAGER_TEMPLATE" => "main",
		"AJAX_REQUEST" => ($bAjax ? "Y" : "N"),
		"SEF_MODE" => "N",
		"CACHE_FILTER" => "N",
		"SHOW_MEASURE" => "Y",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"OFFERS_CART_PROPERTIES" => array(
		),
		"COMPARE_PATH" => "",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		// Отсюда и далее идут дополнительные параметры для корректного отображения цены, кол-ва и кнопки "в корзину"
		"SHOW_COUNTER_LIST" => "Y",
	    "SHOW_ONE_CLICK_BUY" => "Y",
	    "SHOW_QUANTITY" => "Y",
	    "SHOW_QUANTITY_COUNT" => "Y",
	    "SORT_PRICES" => "MINIMUM_PRICE",
	    "USE_ELEMENT_COUNTER" => "Y",
	    "SHOW_DISCOUNT_TIME" => "Y",
		"USE_ONLY_MAX_AMOUNT" => "Y",
		"USE_MIN_AMOUNT" => "Y",
		"MAX_AMOUNT" => "20",
		"MIN_AMOUNT" => "10",
		"USE_STORE" => "N",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"CURRENCY_ID" => "RUB",
		"DEFAULT_COUNT" => "1",
		"SHOW_HINTS" => "Y",
		"OFFER_HIDE_NAME_PROPS" => "N",
	),
	false, array("HIDE_ICONS"=>"Y")
);?>